//
// auto-generated by ops.py
//

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define OPS_2D
#include "ops_lib_cpp.h"

#include "globalvars.h"

//#include "buildinitialfield_kernel.h"

void buildinitialfield() {}
