//
// auto-generated by ops.py
//

#include "globalvars.h"

ops_block fvm2d_grid;

ops_dat facex;
ops_dat facey;
ops_dat cellx;
ops_dat celly;
ops_dat celldx;
ops_dat celldy;
ops_dat facedx;
ops_dat facedy;
ops_dat xcvs;
ops_dat ycvs;
ops_dat xvel0;
ops_dat yvel0;
ops_dat presscorr;
ops_dat density;
ops_dat temperature;
ops_dat xvelhat;
ops_dat yvelhat;

ops_stencil S2D_00;
ops_stencil S2D_00_P10_M10_0P1_0M1;

FILE *fp;

double xmin;
double ymin;
double xmax;
double ymax;
double xlength;
double ylength;
int xcells;
int ycells;
int xL1;
int xL2;
int xL3;
int yM1;
int yM2;
int yM3;
int iter;
