//
// auto-generated by ops.py//

// header
#define OPS_2D
#define OPS_ACC_MACROS
#define OPS_ACC_MD_MACROS
#include "ops_lib_cpp.h"
#ifdef OPS_MPI
#include "ops_mpi_core.h"
#endif

// global constants
extern double xmin;
extern double xmax;
extern int xcells;
extern double ymin;
extern double ymax;
extern int ycells;
extern int xL1;
extern int xL2;
extern int xL3;
extern int yM1;
extern int yM2;
extern int yM3;

void ops_init_backend() {}

// user kernel files
#include "gridsetup_kernel_setupX_seq_kernel.cpp"
