//
// auto-generated by ops.py
//
#include "./OpenACC/fvm2dc_common.h"

#define OPS_GPU

int xdim0_gridsetup_kernel_setupY;
int xdim1_gridsetup_kernel_setupY;
int xdim2_gridsetup_kernel_setupY;
int xdim3_gridsetup_kernel_setupY;
int xdim4_gridsetup_kernel_setupY;
int xdim5_gridsetup_kernel_setupY;
int xdim6_gridsetup_kernel_setupY;

#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC5
#undef OPS_ACC6

#define OPS_ACC0(x, y) (x + xdim0_gridsetup_kernel_setupY * (y))
#define OPS_ACC1(x, y) (x + xdim1_gridsetup_kernel_setupY * (y))
#define OPS_ACC2(x, y) (x + xdim2_gridsetup_kernel_setupY * (y))
#define OPS_ACC3(x, y) (x + xdim3_gridsetup_kernel_setupY * (y))
#define OPS_ACC4(x, y) (x + xdim4_gridsetup_kernel_setupY * (y))
#define OPS_ACC5(x, y) (x + xdim5_gridsetup_kernel_setupY * (y))
#define OPS_ACC6(x, y) (x + xdim6_gridsetup_kernel_setupY * (y))

// user function
inline void gridsetup_kernel_setupY(double *yv_facey, double *y_celly,
                                    double *ydif_celldy, double *ycv_facedy,
                                    double *ycvs, double *ycvr, double *ycvrs,
                                    int *idx) {
  double d_y;
  d_y = (ymax - ymin) / (double)ycells;
}

#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC5
#undef OPS_ACC6

void gridsetup_kernel_setupY_c_wrapper(double *p_a0, double *p_a1, double *p_a2,
                                       double *p_a3, double *p_a4, double *p_a5,
                                       double *p_a6, int *p_a7, int arg_idx0,
                                       int arg_idx1, int x_size, int y_size) {
#ifdef OPS_GPU
#pragma acc parallel deviceptr(p_a0, p_a1, p_a2, p_a3, p_a4, p_a5, p_a6)
#pragma acc loop
#endif
  for (int n_y = 0; n_y < y_size; n_y++) {
#ifdef OPS_GPU
#pragma acc loop
#endif
    for (int n_x = 0; n_x < x_size; n_x++) {
      int arg_idx[] = {arg_idx0 + n_x, arg_idx1 + n_y};
      gridsetup_kernel_setupY(
          p_a0 + n_x * 1 * 1 + n_y * xdim0_gridsetup_kernel_setupY * 1 * 1,
          p_a1 + n_x * 1 * 1 + n_y * xdim1_gridsetup_kernel_setupY * 1 * 1,
          p_a2 + n_x * 1 * 1 + n_y * xdim2_gridsetup_kernel_setupY * 1 * 1,
          p_a3 + n_x * 1 * 1 + n_y * xdim3_gridsetup_kernel_setupY * 1 * 1,
          p_a4 + n_x * 1 * 1 + n_y * xdim4_gridsetup_kernel_setupY * 1 * 1,
          p_a5 + n_x * 1 * 1 + n_y * xdim5_gridsetup_kernel_setupY * 1 * 1,
          p_a6 + n_x * 1 * 1 + n_y * xdim6_gridsetup_kernel_setupY * 1 * 1,
          arg_idx);
    }
  }
}
