//
// auto-generated by ops.py
//
#include "./OpenACC/fvm2dc_common.h"

#define OPS_GPU

int xdim0_gridsetup_kernel_facey;

#undef OPS_ACC0

#define OPS_ACC0(x, y) (x + xdim0_gridsetup_kernel_facey * (y))

// user function
inline void gridsetup_kernel_facey(double *val, int *idx) {

  double d_y;
  if (idx[1] == 0) {
    val[OPS_ACC0(0, 0)] = 0;
  } else if (idx[1] == yM1) {
    val[OPS_ACC0(0, 0)] = ymax;
  } else {
    d_y = (ymax - ymin) / (double)ycells;

    val[OPS_ACC0(0, 0)] = d_y * (idx[1] - 1);
  }
}

#undef OPS_ACC0

void gridsetup_kernel_facey_c_wrapper(double *p_a0, int *p_a1, int arg_idx0,
                                      int arg_idx1, int x_size, int y_size) {
#ifdef OPS_GPU
#pragma acc parallel deviceptr(p_a0)
#pragma acc loop
#endif
  for (int n_y = 0; n_y < y_size; n_y++) {
#ifdef OPS_GPU
#pragma acc loop
#endif
    for (int n_x = 0; n_x < x_size; n_x++) {
      int arg_idx[] = {arg_idx0 + n_x, arg_idx1 + n_y};
      gridsetup_kernel_facey(p_a0 + n_x * 1 * 1 +
                                 n_y * xdim0_gridsetup_kernel_facey * 1 * 1,
                             arg_idx);
    }
  }
}
