//
// auto-generated by ops.py
//
#include "./OpenACC/fvm2dc_common.h"

#define OPS_GPU

int xdim0_gridsetup_kernel_setupX;
int xdim1_gridsetup_kernel_setupX;
int xdim2_gridsetup_kernel_setupX;
int xdim3_gridsetup_kernel_setupX;
int xdim4_gridsetup_kernel_setupX;
int xdim5_gridsetup_kernel_setupX;
int xdim6_gridsetup_kernel_setupX;

#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC5
#undef OPS_ACC6

#define OPS_ACC0(x, y) (x + xdim0_gridsetup_kernel_setupX * (y))
#define OPS_ACC1(x, y) (x + xdim1_gridsetup_kernel_setupX * (y))
#define OPS_ACC2(x, y) (x + xdim2_gridsetup_kernel_setupX * (y))
#define OPS_ACC3(x, y) (x + xdim3_gridsetup_kernel_setupX * (y))
#define OPS_ACC4(x, y) (x + xdim4_gridsetup_kernel_setupX * (y))
#define OPS_ACC5(x, y) (x + xdim5_gridsetup_kernel_setupX * (y))
#define OPS_ACC6(x, y) (x + xdim6_gridsetup_kernel_setupX * (y))

// user function
inline void gridsetup_kernel_setupX(double *xu_facex, double *x_cellx,
                                    double *xdif_celldx, double *xcv_facedx,
                                    double *xcvs, double *xcvi, double *xcvip,
                                    int *idx) {
  double d_x;
  d_x = (xmax - xmin) / (double)xcells;

  if (idx[0] == 0) {
    xu_facex[OPS_ACC0(0, 0)] = xmin;
    x_cellx[OPS_ACC1(0, 0)] = xmin;
    xdif_celldx[OPS_ACC2(0, 0)] = 0.0;
    xcv_facedx[OPS_ACC3(0, 0)] = 0.0;
    xcvs[OPS_ACC4(0, 0)] = 0.0;
    xcvi[OPS_ACC5(0, 0)] = 0.0;
    xcvip[OPS_ACC6(0, 0)] = 0.0;
  } else if (idx[0] == 1) {
    xu_facex[OPS_ACC0(0, 0)] = xmin;
    x_cellx[OPS_ACC1(0, 0)] = xmin + d_x / 2.0;
    xdif_celldx[OPS_ACC2(0, 0)] = d_x / 2.0;
    xcv_facedx[OPS_ACC3(0, 0)] = d_x;
    xcvs[OPS_ACC4(0, 0)] = 0.0;
    xcvi[OPS_ACC5(0, 0)] = 0.0;
    xcvip[OPS_ACC6(0, 0)] = d_x;
  } else if (idx[0] == 2) {
    xu_facex[OPS_ACC0(0, 0)] = d_x * (idx[0] - 1.0);
    x_cellx[OPS_ACC1(0, 0)] = d_x * idx[0] - d_x / 2.0;
    xdif_celldx[OPS_ACC2(0, 0)] = d_x;
    xcv_facedx[OPS_ACC3(0, 0)] = d_x;
    xcvs[OPS_ACC4(0, 0)] = d_x + d_x / 2.0;
    xcvi[OPS_ACC5(0, 0)] = d_x / 2.0;
    xcvip[OPS_ACC6(0, 0)] = d_x / 2.0;

  } else if (idx[0] == xL3 - 1) {
    xu_facex[OPS_ACC0(0, 0)] = d_x * (idx[0] - 1.0);
    x_cellx[OPS_ACC1(0, 0)] = d_x * idx[0] - d_x / 2.0;
    xdif_celldx[OPS_ACC2(0, 0)] = d_x;
    xcv_facedx[OPS_ACC3(0, 0)] = d_x;
    xcvs[OPS_ACC4(0, 0)] = d_x;
    xcvi[OPS_ACC5(0, 0)] = d_x / 2.0;
    xcvip[OPS_ACC6(0, 0)] = d_x / 2.0;

  } else if (idx[0] == xL2 - 1) {
    xu_facex[OPS_ACC0(0, 0)] = xmax - d_x;
    x_cellx[OPS_ACC1(0, 0)] = xmax - d_x / 2.0;
    xdif_celldx[OPS_ACC2(0, 0)] = d_x;
    xcv_facedx[OPS_ACC3(0, 0)] = d_x;
    xcvs[OPS_ACC4(0, 0)] = d_x + d_x / 2.0;
    xcvi[OPS_ACC5(0, 0)] = d_x;
    xcvip[OPS_ACC6(0, 0)] = 0.0;
  } else if (idx[0] == xL1 - 1) {
    xu_facex[OPS_ACC0(0, 0)] = xmax;
    x_cellx[OPS_ACC1(0, 0)] = xmax;
    xdif_celldx[OPS_ACC2(0, 0)] = d_x / 2.0;
    xcv_facedx[OPS_ACC3(0, 0)] = 0.0;
    xcvs[OPS_ACC4(0, 0)] = 0.0;
    xcvi[OPS_ACC5(0, 0)] = 0.0;
    xcvip[OPS_ACC6(0, 0)] = 0.0;
  } else {
    xu_facex[OPS_ACC0(0, 0)] = d_x * (idx[0] - 1.0);
    x_cellx[OPS_ACC1(0, 0)] = d_x * idx[0] - d_x / 2.0;
    xdif_celldx[OPS_ACC2(0, 0)] = d_x;
    xcv_facedx[OPS_ACC3(0, 0)] = d_x;
    xcvs[OPS_ACC4(0, 0)] = d_x;
    xcvi[OPS_ACC5(0, 0)] = d_x / 2.0;
    xcvip[OPS_ACC6(0, 0)] = d_x / 2.0;
  }
}

#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC5
#undef OPS_ACC6

void gridsetup_kernel_setupX_c_wrapper(double *p_a0, double *p_a1, double *p_a2,
                                       double *p_a3, double *p_a4, double *p_a5,
                                       double *p_a6, int *p_a7, int arg_idx0,
                                       int arg_idx1, int x_size, int y_size) {
#ifdef OPS_GPU
#pragma acc parallel deviceptr(p_a0, p_a1, p_a2, p_a3, p_a4, p_a5, p_a6)
#pragma acc loop
#endif
  for (int n_y = 0; n_y < y_size; n_y++) {
#ifdef OPS_GPU
#pragma acc loop
#endif
    for (int n_x = 0; n_x < x_size; n_x++) {
      int arg_idx[] = {arg_idx0 + n_x, arg_idx1 + n_y};
      gridsetup_kernel_setupX(
          p_a0 + n_x * 1 * 1 + n_y * xdim0_gridsetup_kernel_setupX * 1 * 1,
          p_a1 + n_x * 1 * 1 + n_y * xdim1_gridsetup_kernel_setupX * 1 * 1,
          p_a2 + n_x * 1 * 1 + n_y * xdim2_gridsetup_kernel_setupX * 1 * 1,
          p_a3 + n_x * 1 * 1 + n_y * xdim3_gridsetup_kernel_setupX * 1 * 1,
          p_a4 + n_x * 1 * 1 + n_y * xdim4_gridsetup_kernel_setupX * 1 * 1,
          p_a5 + n_x * 1 * 1 + n_y * xdim5_gridsetup_kernel_setupX * 1 * 1,
          p_a6 + n_x * 1 * 1 + n_y * xdim6_gridsetup_kernel_setupX * 1 * 1,
          arg_idx);
    }
  }
}
