//
// auto-generated by ops.py//

#include "./MPI_inline/fvm2dc_common.h"

void ops_init_backend() {}

void ops_decl_const_char2(int dim, char const *type, int size, char *dat,
                          char const *name) {
  if (!strcmp(name, "xmin")) {
    xmin = *(double *)dat;
  } else if (!strcmp(name, "xmax")) {
    xmax = *(double *)dat;
  } else if (!strcmp(name, "xcells")) {
    xcells = *(int *)dat;
  } else if (!strcmp(name, "ymin")) {
    ymin = *(double *)dat;
  } else if (!strcmp(name, "ymax")) {
    ymax = *(double *)dat;
  } else if (!strcmp(name, "ycells")) {
    ycells = *(int *)dat;
  } else if (!strcmp(name, "xL1")) {
    xL1 = *(int *)dat;
  } else if (!strcmp(name, "xL2")) {
    xL2 = *(int *)dat;
  } else if (!strcmp(name, "xL3")) {
    xL3 = *(int *)dat;
  } else if (!strcmp(name, "yM1")) {
    yM1 = *(int *)dat;
  } else if (!strcmp(name, "yM2")) {
    yM2 = *(int *)dat;
  } else if (!strcmp(name, "yM3")) {
    yM3 = *(int *)dat;
  } else {
    printf("error: unknown const name\n");
    exit(1);
  }
}
