//
// auto-generated by ops.py
//
#include "./MPI_inline/fvm2dc_common.h"

int xdim0_gridsetup_kernel_setupY;
int xdim1_gridsetup_kernel_setupY;
int xdim2_gridsetup_kernel_setupY;
int xdim3_gridsetup_kernel_setupY;
int xdim4_gridsetup_kernel_setupY;
int xdim5_gridsetup_kernel_setupY;
int xdim6_gridsetup_kernel_setupY;

#define OPS_ACC0(x, y)                                                         \
  (n_x * 1 + n_y * xdim0_gridsetup_kernel_setupY * 1 + x +                     \
   xdim0_gridsetup_kernel_setupY * (y))
#define OPS_ACC1(x, y)                                                         \
  (n_x * 1 + n_y * xdim1_gridsetup_kernel_setupY * 1 + x +                     \
   xdim1_gridsetup_kernel_setupY * (y))
#define OPS_ACC2(x, y)                                                         \
  (n_x * 1 + n_y * xdim2_gridsetup_kernel_setupY * 1 + x +                     \
   xdim2_gridsetup_kernel_setupY * (y))
#define OPS_ACC3(x, y)                                                         \
  (n_x * 1 + n_y * xdim3_gridsetup_kernel_setupY * 1 + x +                     \
   xdim3_gridsetup_kernel_setupY * (y))
#define OPS_ACC4(x, y)                                                         \
  (n_x * 1 + n_y * xdim4_gridsetup_kernel_setupY * 1 + x +                     \
   xdim4_gridsetup_kernel_setupY * (y))
#define OPS_ACC5(x, y)                                                         \
  (n_x * 1 + n_y * xdim5_gridsetup_kernel_setupY * 1 + x +                     \
   xdim5_gridsetup_kernel_setupY * (y))
#define OPS_ACC6(x, y)                                                         \
  (n_x * 1 + n_y * xdim6_gridsetup_kernel_setupY * 1 + x +                     \
   xdim6_gridsetup_kernel_setupY * (y))

// user function

void gridsetup_kernel_setupY_c_wrapper(
    double *restrict yv_facey, double *restrict y_celly,
    double *restrict ydif_celldy, double *restrict ycv_facedy,
    double *restrict ycvs, double *restrict ycvr, double *restrict ycvrs,
    int *restrict idx, int arg_idx0, int arg_idx1, int x_size, int y_size) {
#pragma omp parallel for
  for (int n_y = 0; n_y < y_size; n_y++) {
    for (int n_x = 0; n_x < x_size; n_x++) {
      int idx[] = {arg_idx0 + n_x, arg_idx1 + n_y};

      double d_y;
      d_y = (ymax - ymin) / (double)ycells;
    }
  }
}
#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC5
#undef OPS_ACC6
