//
// auto-generated by ops.py
//
#include "./MPI_inline/fvm2dc_common.h"

int xdim0_gridsetup_kernel_xcvs;
int xdim1_gridsetup_kernel_xcvs;

#define OPS_ACC0(x, y)                                                         \
  (n_x * 1 + n_y * xdim0_gridsetup_kernel_xcvs * 1 + x +                       \
   xdim0_gridsetup_kernel_xcvs * (y))
#define OPS_ACC1(x, y)                                                         \
  (n_x * 1 + n_y * xdim1_gridsetup_kernel_xcvs * 1 + x +                       \
   xdim1_gridsetup_kernel_xcvs * (y))

// user function

void gridsetup_kernel_xcvs_c_wrapper(double *restrict xcvs,
                                     const double *restrict celldx,
                                     int *restrict idx, int arg_idx0,
                                     int arg_idx1, int x_size, int y_size) {
#pragma omp parallel for
  for (int n_y = 0; n_y < y_size; n_y++) {
    for (int n_x = 0; n_x < x_size; n_x++) {
      int idx[] = {arg_idx0 + n_x, arg_idx1 + n_y};

      if (idx[0] == 0) {
      } else if (idx[0] == xL1) {
      } else {

        xcvs[OPS_ACC0(0, 0)] = celldx[OPS_ACC1(0, 0)];
      }
    }
  }
}
#undef OPS_ACC0
#undef OPS_ACC1
