//
// auto-generated by ops.py
//
#include "./MPI_inline/fvm2dc_common.h"

int xdim0_gridsetup_kernel_facex;

#define OPS_ACC0(x, y)                                                         \
  (n_x * 1 + n_y * xdim0_gridsetup_kernel_facex * 1 + x +                      \
   xdim0_gridsetup_kernel_facex * (y))

// user function

void gridsetup_kernel_facex_c_wrapper(double *restrict val, int *restrict idx,
                                      int arg_idx0, int arg_idx1, int x_size,
                                      int y_size) {
#pragma omp parallel for
  for (int n_y = 0; n_y < y_size; n_y++) {
    for (int n_x = 0; n_x < x_size; n_x++) {
      int idx[] = {arg_idx0 + n_x, arg_idx1 + n_y};

      double d_x;
      if (idx[0] == 0) {
        val[OPS_ACC0(0, 0)] = 0;
      } else if (idx[0] == xL1) {
        val[OPS_ACC0(0, 0)] = xmax;
      } else {
        d_x = (xmax - xmin) / (double)xcells;

        val[OPS_ACC0(0, 0)] = d_x * (idx[0] - 1);
      }
    }
  }
}
#undef OPS_ACC0
