//
// auto-generated by ops.py
//
#include "./MPI_inline/fvm2dc_common.h"

int xdim0_gridsetup_kernel_facey;

#define OPS_ACC0(x, y)                                                         \
  (n_x * 1 + n_y * xdim0_gridsetup_kernel_facey * 1 + x +                      \
   xdim0_gridsetup_kernel_facey * (y))

// user function

void gridsetup_kernel_facey_c_wrapper(double *restrict val, int *restrict idx,
                                      int arg_idx0, int arg_idx1, int x_size,
                                      int y_size) {
#pragma omp parallel for
  for (int n_y = 0; n_y < y_size; n_y++) {
    for (int n_x = 0; n_x < x_size; n_x++) {
      int idx[] = {arg_idx0 + n_x, arg_idx1 + n_y};

      double d_y;
      if (idx[1] == 0) {
        val[OPS_ACC0(0, 0)] = 0;
      } else if (idx[1] == yM1) {
        val[OPS_ACC0(0, 0)] = ymax;
      } else {
        d_y = (ymax - ymin) / (double)ycells;

        val[OPS_ACC0(0, 0)] = d_y * (idx[1] - 1);
      }
    }
  }
}
#undef OPS_ACC0
