//
// auto-generated by ops.py
//
#include "./MPI_inline/fvm2dc_common.h"

int xdim0_gridsetup_kernel_setupY_Cartesian;
int xdim1_gridsetup_kernel_setupY_Cartesian;
int xdim2_gridsetup_kernel_setupY_Cartesian;
int xdim3_gridsetup_kernel_setupY_Cartesian;
int xdim4_gridsetup_kernel_setupY_Cartesian;
int xdim5_gridsetup_kernel_setupY_Cartesian;
int xdim6_gridsetup_kernel_setupY_Cartesian;

#define OPS_ACC0(x, y)                                                         \
  (n_x * 1 + n_y * xdim0_gridsetup_kernel_setupY_Cartesian * 1 + x +           \
   xdim0_gridsetup_kernel_setupY_Cartesian * (y))
#define OPS_ACC1(x, y)                                                         \
  (n_x * 1 + n_y * xdim1_gridsetup_kernel_setupY_Cartesian * 1 + x +           \
   xdim1_gridsetup_kernel_setupY_Cartesian * (y))
#define OPS_ACC2(x, y)                                                         \
  (n_x * 1 + n_y * xdim2_gridsetup_kernel_setupY_Cartesian * 1 + x +           \
   xdim2_gridsetup_kernel_setupY_Cartesian * (y))
#define OPS_ACC3(x, y)                                                         \
  (n_x * 1 + n_y * xdim3_gridsetup_kernel_setupY_Cartesian * 1 + x +           \
   xdim3_gridsetup_kernel_setupY_Cartesian * (y))
#define OPS_ACC4(x, y)                                                         \
  (n_x * 1 + n_y * xdim4_gridsetup_kernel_setupY_Cartesian * 1 + x +           \
   xdim4_gridsetup_kernel_setupY_Cartesian * (y))
#define OPS_ACC5(x, y)                                                         \
  (n_x * 1 + n_y * xdim5_gridsetup_kernel_setupY_Cartesian * 1 + x +           \
   xdim5_gridsetup_kernel_setupY_Cartesian * (y))
#define OPS_ACC6(x, y)                                                         \
  (n_x * 1 + n_y * xdim6_gridsetup_kernel_setupY_Cartesian * 1 + x +           \
   xdim6_gridsetup_kernel_setupY_Cartesian * (y))

// user function

void gridsetup_kernel_setupY_Cartesian_c_wrapper(
    double *restrict yv_facey, double *restrict y_celly,
    double *restrict ydif_celldy, double *restrict ycv_facedy,
    double *restrict ycvs, double *restrict ycvr, double *restrict ycvrs,
    int *restrict idx, int arg_idx0, int arg_idx1, int x_size, int y_size) {
#pragma omp parallel for
  for (int n_y = 0; n_y < y_size; n_y++) {
    for (int n_x = 0; n_x < x_size; n_x++) {
      int idx[] = {arg_idx0 + n_x, arg_idx1 + n_y};

      double d_y;
      d_y = (ymax - ymin) / (double)ycells;

      if (idx[1] == 0) {
        yv_facey[OPS_ACC0(0, 0)] = ymin;
        y_celly[OPS_ACC1(0, 0)] = ymin;
        ydif_celldy[OPS_ACC2(0, 0)] = 0.0;
        ycv_facedy[OPS_ACC3(0, 0)] = 0.0;
        ycvs[OPS_ACC4(0, 0)] = 0.0;
        ycvr[OPS_ACC5(0, 0)] = 0.0;
        ycvrs[OPS_ACC6(0, 0)] = 0.0;
      } else if (idx[1] == 1) {
        yv_facey[OPS_ACC0(0, 0)] = ymin;
        y_celly[OPS_ACC1(0, 0)] = ymin + d_y / 2.0;
        ydif_celldy[OPS_ACC2(0, 0)] = d_y / 2.0;
        ycv_facedy[OPS_ACC3(0, 0)] = d_y;
        ycvs[OPS_ACC4(0, 0)] = 0.0;
        ycvr[OPS_ACC5(0, 0)] = 0.0;
        ycvrs[OPS_ACC6(0, 0)] = d_y;
      } else if (idx[1] == 2) {

        yv_facey[OPS_ACC0(0, 0)] = d_y * (idx[1] - 1.0);
        y_celly[OPS_ACC1(0, 0)] = d_y * idx[1] - d_y / 2.0;
        ydif_celldy[OPS_ACC2(0, 0)] = d_y;
        ycv_facedy[OPS_ACC3(0, 0)] = d_y;
        ycvs[OPS_ACC4(0, 0)] = d_y + d_y / 2.0;
        ycvr[OPS_ACC5(0, 0)] = d_y / 2.0;
        ycvrs[OPS_ACC6(0, 0)] = d_y / 2.0;

      } else if (idx[1] == yM3 - 1) {
        yv_facey[OPS_ACC0(0, 0)] = d_y * (idx[1] - 1.0);
        y_celly[OPS_ACC1(0, 0)] = d_y * idx[1] - d_y / 2.0;
        ydif_celldy[OPS_ACC2(0, 0)] = d_y;
        ycv_facedy[OPS_ACC3(0, 0)] = d_y;
        ycvs[OPS_ACC4(0, 0)] = d_y;
        ycvr[OPS_ACC5(0, 0)] = d_y / 2.0;
        ycvrs[OPS_ACC6(0, 0)] = d_y / 2.0;

      } else if (idx[1] == yM2 - 1) {
        yv_facey[OPS_ACC0(0, 0)] = ymax - d_y;
        y_celly[OPS_ACC1(0, 0)] = ymax - d_y / 2.0;
        ydif_celldy[OPS_ACC2(0, 0)] = d_y;
        ycv_facedy[OPS_ACC3(0, 0)] = d_y;
        ycvs[OPS_ACC4(0, 0)] = d_y + d_y / 2.0;
        ycvr[OPS_ACC5(0, 0)] = d_y;
        ycvrs[OPS_ACC6(0, 0)] = 0.0;

      } else if (idx[1] == yM1 - 1) {
        yv_facey[OPS_ACC0(0, 0)] = ymax;
        y_celly[OPS_ACC1(0, 0)] = ymax;
        ydif_celldy[OPS_ACC2(0, 0)] = d_y / 2.0;
        ycv_facedy[OPS_ACC3(0, 0)] = 0.0;
        ycvs[OPS_ACC4(0, 0)] = 0.0;
        ycvr[OPS_ACC5(0, 0)] = 0.0;
        ycvrs[OPS_ACC6(0, 0)] = 0.0;

      } else {
        yv_facey[OPS_ACC0(0, 0)] = d_y * (idx[1] - 1.0);
        y_celly[OPS_ACC1(0, 0)] = d_y * idx[1] - d_y / 2.0;
        ydif_celldy[OPS_ACC2(0, 0)] = d_y;
        ycv_facedy[OPS_ACC3(0, 0)] = d_y;
        ycvs[OPS_ACC4(0, 0)] = d_y;
        ycvr[OPS_ACC5(0, 0)] = d_y / 2.0;
        ycvrs[OPS_ACC6(0, 0)] = d_y / 2.0;
      }
    }
  }
}
#undef OPS_ACC0
#undef OPS_ACC1
#undef OPS_ACC2
#undef OPS_ACC3
#undef OPS_ACC4
#undef OPS_ACC5
#undef OPS_ACC6
